# github.com/frapposelli/wwhrd
# wwhrd check

whitelist:
  - Apache-2.0
  - MIT
  - BSD-2-Clause
  - BSD-3-Clause

exceptions:
  - github.com/aws/aws-xray-sdk-go/... # Uses Apache-2.0
  - sigs.k8s.io/yaml/... # Uses MIT
  - github.com/gogo/protobuf/... # Uses 3-clause BSD