version: 0.2
env:
  variables:
    GOPATH: /go
    GOBIN: /go/bin
    ROOTPATH: /go/src/github.com/swoldemi/amazon-ecr-repository-compliance-webhook

phases:
  install:
    runtime-versions:
      golang: 1.14
    commands:
      - pip3 install -U aws-sam-cli aws-sam-translator && sam --version
      - mkdir -p $ROOTPATH
      - make install-tools
      - ln -s "${CODEBUILD_SRC_DIR}" $ROOTPATH

  build:
    commands:
      - make clean && GOGC=10 make && make sam-package && chmod +x ./scripts/publish.sh && ./scripts/publish.sh