version: 0.2
env:
  variables:
    GOPATH: /go
    GOBIN: /go/bin
    ROOTPATH: /go/src/github.com/aws-samples/amazon-ecr-repository-compliance-webhook

phases:
  install:
    runtime-versions:
      golang: 1.14
    commands:
      - mkdir -p "$ROOTPATH"
      - make install-tools && sam --version
      - ln -s "${CODEBUILD_SRC_DIR}" $ROOTPATH
  pre_build:
    commands:
      - go mod vendor && wwhrd check -q && rm -rf vendor
  build:
    commands:
      - make clean && make && make sam-package
  post_build:
    commands:
      - chmod +x ./scripts/publish.sh && ./scripts/publish.sh
