version: 0.2
env:
  variables:
    GOPATH: /go
    GOBIN: /go/bin
    ROOTPATH: /go/src/github.com/swoldemi/ecr-repository-compliance-webhook
phases:
  install:
    runtime-versions:
      golang: 1.13
    commands:
      - pip3 install -U aws-sam-cli cfn-lint aws-sam-translator
      - sed -i '3s/go 1.14/go 1.13/' go.mod # Until CodeBuild supports Go 1.14
      - mkdir -p $ROOTPATH
      - go get golang.org/x/lint/golint
      - go get mvdan.cc/gofumpt/gofumports
      - go get mvdan.cc/gofumpt
      - curl -L https://git.io/vp6lP | bash -s -- -b /go/bin
      - go get github.com/golangci/golangci-lint/cmd/golangci-lint
      - go get github.com/gojp/goreportcard/cmd/goreportcard-cli
      - go mod tidy && go mod download
      - ln -s "${CODEBUILD_SRC_DIR}" $ROOTPATH

  pre_build:
    commands:
      - sam --version && cfn-lint --version
      - make tmpl check test

  build:
    commands:
      - make build && make sam-package

  post_build:
    commands:
      - chmod +x ./scripts/publish.sh && ./scripts/publish.sh