apiVersion: apps/v1 
kind: Deployment
metadata:
  name: test
  namespace: test-namespace
spec:
  selector:
    matchLabels:
      app: test
  replicas: 2 
  template:
    metadata:
      labels:
        app: test
    spec:
      containers:
      - name: test
        image: nginx:latest
        ports:
        - containerPort: 80