AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31

Metadata:
  AWS::ServerlessRepo::Application:
    Name: ecr-repository-compliance-webhook
    Description: "Create snapshots of EBS volumes, at an interval, with cross-account support."
    Author: Simon Woldemichael
    SpdxLicenseId: Apache-2.0
    LicenseUrl: LICENSE
    ReadmeUrl: README.md
    Labels: ["kubernetes", "validating", "admission", "webhook", "eks"]
    HomePageUrl: https://github.com/swoldemi/ecr-repository-compliance-webhook
    SemanticVersion: 1.0.0
    SourceCodeUrl: https://github.com/swoldemi/ecr-repository-compliance-webhook

Parameters:
# TODO

Resources:
  ECRRepositoryComplianceWebhookExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action:
              - sts:AssumeRole
            Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
        Version: "2012-10-17"
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyDocument:
            Statement:
              - Action:
                  - ec2:CreateSnapshot
                  - ec2:CreateTags
                  - ec2:DescribeVolumes
                  - cloudwatch:PutMetricData
                  - xray:PutTraceSegments
                Effect: Allow
                Resource: "*"
            Version: "2012-10-17"
          PolicyName: ECRRepositoryComplianceWebhookLambdaPolicy

  ECRRepositoryComplianceWebhookFunction:
    Type: AWS::Serverless::Function
    Description: Lambda handler for ecr-repository-compliance-webhook
    Properties:
      FunctionName: ecr-repository-compliance-webhook
      Handler: main
      Runtime: go1.x
      Tracing: Active
      MemorySize: 128
      Role: !GetAtt ECRRepositoryComplianceWebhookExecutionRole.Arn
      Timeout: 15
      # TODO - Add Gateway

  

 

Outputs:
  LambdaFunctionARN:
    Description: ECRRepositoryComplianceWebhook Lambda Function ARN
    Value: !GetAtt ECRRepositoryComplianceWebhookFunction.Arn
  APIGatewayEndpoint:
    # TODO


