AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: |
  A Kubernetes ValidatingWebhookConfiguration and serverless backend:
  Deny Pods with container images that don't meet your compliance requirements.

Metadata:
  AWS::ServerlessRepo::Application:
    Name: amazon-ecr-repository-compliance-webhook
    Description: "A Kubernetes ValidatingWebhookConfiguration and serverless backend: Deny Pods with container images that don't meet your compliance requirements"
    Author: Simon Woldemichael
    SpdxLicenseId: Apache-2.0
    LicenseUrl: LICENSE
    ReadmeUrl: README.md
    Labels: ["kubernetes", "validating", "admission", "webhook", "eks", "ecr"]
    HomePageUrl: https://github.com/swoldemi/amazon-ecr-repository-compliance-webhook
    SemanticVersion: 1.3.1
    SourceCodeUrl: https://github.com/swoldemi/amazon-ecr-repository-compliance-webhook

Parameters:
  RegistryRegion:
    Type: String
    Description: Optional. What AWS region should this Lambda function interact with ECR in?
    Default: ""

Conditions:
  HasRegistryRegion: !Not [!Equals [!Ref RegistryRegion, ""]]

Resources:
  ECRRepositoryComplianceWebhookExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action:
              - sts:AssumeRole
            Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
        Version: "2012-10-17"
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyDocument:
            Statement:
              - Action:
                  - ecr:DescribeRepositories
                  - xray:PutTraceSegments
                  - ecr:DescribeImageScanFindings
                Effect: Allow
                Resource: "*"
            Version: "2012-10-17"
          PolicyName: ECRRepositoryComplianceWebhookLambdaPolicy

  ECRRepositoryComplianceWebhookAPIGateway:
    Type: AWS::Serverless::HttpApi
    Properties:
      StageName: Prod

  ECRRepositoryComplianceWebhookFunction:
    Type: AWS::Serverless::Function
    Description: Lambda handler for amazon-ecr-repository-compliance-webhook
    Properties:
      FunctionName: amazon-ecr-repository-compliance-webhook
      Handler: main
      Runtime: go1.x
      Tracing: Active
      MemorySize: 128
      Role: !GetAtt ECRRepositoryComplianceWebhookExecutionRole.Arn
      Timeout: 15
      Environment:
        Variables:
          REGISTRY_REGION: !If [HasRegistryRegion, !Ref RegistryRegion, !Ref "AWS::NoValue"]
      Events:
        ValidationEvent:
          Type: HttpApi
          Properties:
            Path: /check-image-compliance
            Method: post
            ApiId: !Ref ECRRepositoryComplianceWebhookAPIGateway

  ConfigAPIGatewayLambdaInvoke:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref ECRRepositoryComplianceWebhookFunction
      Principal: apigateway.amazonaws.com

Outputs:
  WebhookURL:
    Description: "ValidatingWebhookConfiguration invocation URL"
    Value: !Sub "https://${ECRRepositoryComplianceWebhookAPIGateway}.execute-api.${AWS::Region}.amazonaws.com/Prod/check-image-compliance"
