apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
  name: ecr-repository-compliance-webhook-config
  labels:
    app: ecr-repository-compliance-webhook
webhooks:
  - name: ecrpolicies.amazonaws.com
    clientConfig:
      url: https://"${APIGW}"/check-repos
    rules:
      - apiGroups: ["apps"]
        apiVersions: ["v1"]
        operations: ["CREATE"]
        resources: ["pods"]
    namespaceSelector:
      matchLabels:
        ecr-repository-compliance-webhook: enabled
