apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
  name: ecr-repository-compliance-webhook-config
  labels:
    app: ecr-repository-compliance-webhook
webhooks:
  - name: ecrpolicies.amazonaws.com
    timeoutSeconds: 8
    failurePolicy: Fail # v1beta1 default is Ignore 
    clientConfig:
      url: https://<YOUR_APIGATEWAY_ID>.execute-api.<YOUR_REGION>.amazonaws.com/Prod/check-image-compliance
    rules:
      - apiGroups: [""]
        apiVersions: ["v1"]
        operations: ["CREATE"]
        resources: ["pods"]
